"Console Error
Error: An unexpected response was received from the server.

Call Stack 1" - Probably a timeout error

We might need to use more parallel generation. Or is there a way to finish the generation process and start another and after doing that we group them?